export const featuredSelfStorages = [
  {
    id: 1,
    image: require("../assets/images/f_storage1.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 2,
    image: require("../assets/images/f_storage2.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 3,
    image: require("../assets/images/f_storage3.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
];

export const activeSelfStorages = [
  {
    id: 1,
    image: require("../assets/images/a_storage1.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 2,
    image: require("../assets/images/a_storage2.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 3,
    image: require("../assets/images/a_storage3.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 4,
    image: require("../assets/images/a_storage4.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 5,
    image: require("../assets/images/a_storage5.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 6,
    image: "",
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 7,
    image: require("../assets/images/a_storage3.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 8,
    image: require("../assets/images/a_storage1.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 9,
    image: "",
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
  {
    id: 10,
    image: require("../assets/images/a_storage5.png"),
    location: "Jersy City, NJ",
    units: 89,
    occupancy: 50,
    size: 40233,
  },
];
